name: Slack DM Reply Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # 5分ごとに実行
  workflow_dispatch:

jobs:
  reply_to_dm:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存関係をインストール
        run: pip install requests

      - name: Slack DM チェック＆返信
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_USER_ID: ${{ secrets.SLACK_USER_ID }}
        run: python reply_to_dm.py
