name: Slack Auto Post Test

on:
  schedule:
    - cron: '*/30 * * * *'  # 毎日午前 0 時 (UTC)
  workflow_dispatch:

jobs:
  post_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存関係をインストール
        run: pip install -r requirements.txt

      - name: Gemini と Slack を使った投稿
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  # GitHub Secrets から取得
          SLACK_USER_ID: ${{ secrets.SLACK_USER_ID }}  # GitHub Secrets から取得
        run: python gemini_to_slack.py
